development:
  :concurrency: 5

staging:
  :concurrency: 10

production:
  :concurrency: 10

:max_retries: 5

:queues:
  - sensor_dashboard_production_default
  - sensor_dashboard_development_default
